spring:
  application:
   name: ProductServiceProducer
  datasource:
    url: jdbc:h2:mem:producdb
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

#Swagger openAPI docs
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
