spring:
  application:
   name: product-service-producer
  datasource:
    url: jdbc:h2:mem:productdb
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true

spring-doc:
  api-doc:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 9091

h2:
  console:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka