server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: spring-cloud-api-gateway
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
